### ISSUE TITLE
The new "select" method doesn't work well with the dev tools extension

### ISSUE THREAD

**Issue by rubyboy** [InfomediaLtd/angular2-redux#13]
The "select" method doesn't work when the dev tools extension is enabled (https://github.com/zalmoxisus/redux-devtools-extension).

You can see that by adding the following line into the AppComponent of the example app in the project:
```js
      appStore.select((state)=>state).subscribe((state)=>console.log(state));
      // this won't work. Looking at the object outputted above shows why
      appStore.select("counter").subscribe((counter)=>console.log("counter",counter));
```

You need to have the extension installed (otherwise, it won't enable it)

**Comment by micha149** [comment]
Not a problem of `angular2-redux`. This is a problem of the dev tools, because it corrupts reduxs observable value. I already made a ticket on [redux-devtools](https://github.com/gaearon/redux-devtools/issues/274) and [redux](https://github.com/reactjs/redux/issues/1675). Also [fixed the issue](https://github.com/gaearon/redux-devtools/pull/275) but a bit nasty, so @gaearon will look to fix it in redux 4.0.0…

**Comment by rubyboy** [comment]
@micha149 thanks for the explanation and links. Much appreciated!
After starting to use the new "select" function I don't know how I could live without it :)

I'll leave this issue open until it's solved for those using this library and the dev tools.

**Comment by gaearon** [comment]
Should be solved in DevTools 3.3.0.

**Comment by rubyboy** [comment]
New version of the Chrome extension has been released and this bug has now been solved.
Thanks heaps @gaearon @zalmoxisus @micha149

**Comment by rubyboy** [comment]
https://github.com/zalmoxisus/redux-devtools-extension/issues/106
